runtime: go111
env: standard
service: 'wargroovy-api'
env_variables:
  PORT: 8080
  jwt_secret: Dnip44WoadZayKF6

  # See https://godoc.org/github.com/lib/pq
  POSTGRES_CONNECTION: "user=postgres password=3kEp30qJlcf7Itl1 dbname=production host=/cloudsql/wargroovy:us-central1:wargroovy-production"

  STORAGE_BUCKET_NAME: "wargroovy.appspot.com"
beta_settings:
  cloud_sql_instances: wargroovy:us-central1:wargroovy-production
handlers:
- url: /.*
  script: auto