# Build the module.
steps:
- name: 'ubuntu'
  args: ['bash', 'pre-deploy.sh']
  dir: 'web'
- name: 'golang'
  env: ['GO111MODULE=on']
  args: ['go', 'build', './...']
  dir: 'web'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']
  dir: 'web'
timeout: '1600s'